name: Auto Record TikTok Live

on:
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          python -m pip install --upgrade pip
          pip install .

      - name: Run Live Recorder
        run: |
          python -u src/main.py -user Sarujaanu786 -mode automatic

      - name: Upload Video
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tiktok-recording
          path: recordings/
